Manga chan/list parser
Sora-reader/backend pull request #104
Opened 2021-08-20 14:12 UTC by MariaAfanasyeva

### Описание

Сделала list-parser для manga-chan

-------

2021-08-20 14:54 UTC, dhvcc commented
Лучше бы убрать парсер Anibel из этого ПРа
Плюс лучше бы ребейснуть мерджи девелопа, что бы по итогу вышел 1 коммит
@MariaAfanasyeva

2021-08-22 21:34 UTC, NikDark reviewed
По поводу последнего объединения это всего лишь предложение
Можешь использовать и своё какое-то решение
Можно написать замыкания еще наверное
В общем что захочешь

2021-08-22 21:34 UTC, NikDark commented on apps/parse/manga_chan/list_parser/manga_spider.py
> +            title = titles[-1]
Давай может получать `alt_title` через XPath `//div[@class = "manga_row1"]//a[@class = "title_link"]/@title`
Также full_title состоит из `alt_title` + 'пробел' + '(' + `title` + ')'
Не нужна будет проверка ниже `if alt_title != title`

2021-08-22 21:34 UTC, NikDark commented on apps/parse/manga_chan/list_parser/pipelines.py
> +            raise KeyError(message)
Я думаю что после изменений выше, этот код будет не нужен, потому что у нас как минимум название будет содержать `alt_title`. А если нету даже `alt_title` то это скорее всего и на сайте нету. Ну, можно на крайний случай добавить проверку в `manga_spider`

2021-08-22 21:34 UTC, NikDark commented on apps/parse/parsers.py
> +    )
Объедини пожалуйста `readmanga_parser` и `manga_chan_parser`, а то здесь только одна переменная отличается
Можно написать dict который будет содержать в себе 
```python
spiders = {
    Manga.SOURCE_MAP.get("https://manga-chan.me") : {
        "spider": MangaChanSpider,
        "settings": MANGA_CHAN_SETTINGS_PATH
    }
}
```

2021-08-22 21:34 UTC, NikDark commented on apps/parse/parsers.py
> +        LIST_PARSER: manga_chan_parser,
ну и здесь доставать из дикта нашего паука
- также не забудь поменять в `ReadManga`
```py
spiders.get(Manga.SOURCE_MAP.get("https://manga-chan.me"))
```

2021-08-26 12:37 UTC, dhvcc requested changes
Надо починить историю коммитов + пара микро-фиксов

2021-08-26 12:37 UTC, dhvcc commented on .github/workflows/ec2-deploy.yml
> +  workflow_run:
А это чего тут делает?)

2021-08-26 12:37 UTC, dhvcc commented on .gitignore
> +.nohup.out
Ты, видимо, подтянула мой код, но не коммиты

2021-08-26 12:37 UTC, dhvcc commented on apps/parse/models.py
> +    popularity = models.IntegerField(default=0)
А это код Никиты

2021-08-26 12:37 UTC, dhvcc commented on apps/parse/parsers.py
> +    )
Давай это позже обсудим, в контексте абстракции не только этой функции

2021-08-26 12:37 UTC, dhvcc commented on manga_reader/settings.py
> +SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
мой код, но не коммит

2021-08-26 12:37 UTC, dhvcc commented on pyproject.toml
> +Werkzeug = "0.16.0"
:eyes:

2021-08-30 16:31 UTC, closed without merging