Inject poetry in the project, small refactor, impementation of JWT
Sora-reader/backend pull request #2
Opened 2021-01-31 14:53 UTC by EgorEna

Перезалив пр

2021-02-01 08:33 UTC, nomilkinmyhome requested changes

2021-02-01 08:33 UTC, nomilkinmyhome commented on backend/main.py
> +import uvicorn
Нужно прогнать линтером. По pep8 сначала импортируется стдлиб, потом сторонние библиотеки, потом модули проекта. Все импорты разделяются отступом.

2021-02-01 08:33 UTC, nomilkinmyhome commented on backend/main.py
> +app = FastAPI()
Инициализировать приложение нужно в фабрике, как во фласке (https://flask.palletsprojects.com/en/1.1.x/patterns/appfactories/).

2021-02-01 08:33 UTC, nomilkinmyhome commented on backend/models/models.py
> +Base: DeclarativeMeta = declarative_base()
models.py - плохое название для модуля, который находится внутри пакета models. Инициализация Base должна происходить вообще в другом месте. Можно создать db.py и перенести Base туда. Пусть в пакете models лежат только модели алхимии, а модели пидантика вынеси в отдельный пакет и назови его, например, schemas или serializers, как больше нравится.

2021-02-01 08:33 UTC, nomilkinmyhome commented on backend/settings.py
> +DATABASE_URL = "sqlite:///./db.sqlite3"
Нужно брать DATABASE_URL из переменных окружения.

2021-02-01 08:33 UTC, nomilkinmyhome commented on backend/settings.py
> +SECRET = "FMLKDFJKSDFJldsjcflsdfklsdjlf"
Токены и прочую sensitive information также нужно хранить в переменных окружения. Можешь взять для этого envparse. Когда добавишь .env-файл, не забудь добавить и .env.example.

2021-02-01 08:33 UTC, nomilkinmyhome commented on backend/settings.py
> +engine = create_engine(
Инициализация engine также должна происходить либо в main.py, либо в db.py, о котором я писала выше.

2021-02-01 08:33 UTC, nomilkinmyhome commented on backend/settings.py
> +jwt_authentication = JWTAuthentication(secret=SECRET, lifetime_seconds=3600)
Инициализация jwt должна быть в фабрике приложения.

2021-02-02 09:35 UTC, dhvcc commented on backend/main.py
> +import uvicorn
> Нужно прогнать линтером. По pep8 сначала импортируется стдлиб, потом сторонние библиотеки, потом модули проекта. Все импорты разделяются отступом.

На такие ошибки пока можно закрыть глаза, есть тикеты по настройке линтеров и форматтеров

2021-02-18 21:03 UTC, closed without merging