added django admin models configuration
Sora-reader/backend pull request #45
Opened 2021-05-24 18:57 UTC by zym43210

2021-05-24 19:06 UTC, dhvcc commented
@zym43210 не забывай юзать мейкфайл `make check` `mak fix`

2021-05-25 19:14 UTC, zym43210 commented
@dhvcc Старина можешь чекать

2021-05-26 11:18 UTC, dhvcc requested changes

2021-05-26 11:18 UTC, dhvcc commented on apps/core/admin_mixins.py
> +        return format_html("<img src='{}'  width='25' height='25' />".format(obj.image_url))
Предлагаю такой вариант
```python
def get_image(self, obj):
        style = "max-height: 100px; border-radius: 3px;"
        return format_html(f"<img src='{obj.image_url}' style='{str(style)}' />")
```

2021-05-26 11:18 UTC, dhvcc commented on apps/readmanga_parser/admin.py
> +        "get_image",
Давай картинку сразу после названия, а не в конец

2021-05-26 11:18 UTC, dhvcc commented on apps/readmanga_parser/admin.py
> +    def genres_list(self, obj):
Давай лучше фабрику напишем, как тут https://github.com/ebertti/django-admin-easy
Пока лучше много сторонних пакетов не добавлять. Напишем свои ютилы, которые будут работать, а там посмотрим

2021-05-26 11:18 UTC, dhvcc commented on apps/readmanga_parser/models.py
> +    def get_admin_url(self):
Давай это вынесем в базовый класс для наших моделей

2021-05-26 11:18 UTC, dhvcc commented on apps/core/models_mixins.py
> +        return f"<{classname}: {self.name}, pk: {self.pk}>"
Тут после не хватает чего-то по типу
```python
...
class BaseModel(TimeStampedModel, ReprMixin, models.Model):
    class Meta:
        abstract = True
```
для всех наших моделей

2021-05-26 11:19 UTC, dhvcc commented
Отличный ПР, хороший код
Какие-то вещи я не совсем хорошо объяснил, когда давал ТЗ, поэтому так много комментов, это моя ошибка
А в целом всё отлично

2021-05-29 13:03 UTC, dhvcc approved these changes

2021-05-29 13:03 UTC, merged