Parsing/parse chapters
Sora-reader/backend pull request #68
Opened 2021-06-26 10:42 UTC by NikDark

### Описание

-------

closes #54

2021-06-28 08:33 UTC, dhvcc requested changes

2021-06-28 08:33 UTC, dhvcc commented on apps/parse/readmanga/chapter_parser/parse.py
> +    links: list[str] = [elem.text for elem in chapters_rss.findall(LINK_TAG)]
Надо оставлять элементы ссылками, что бы удобнее было запрашивать

2021-06-29 12:49 UTC, dhvcc commented
@NikDark resolve merge conflict pls

2021-06-29 14:52 UTC, NikDark commented
Merge conflicts is resolved

2021-06-30 10:49 UTC, dhvcc approved these changes
👍

2021-06-30 11:40 UTC, merged