Return manga-rating in the readmanga in the max scale as 5
Sora-reader/backend pull request #91
Opened 2021-07-23 08:35 UTC by NikDark

Create one rating format for the readmanga and mangalive
Readmanga
![Screenshot from 2021-07-23 11-33-20](https://user-images.githubusercontent.com/50526884/126756885-ec1b1b8e-4360-4781-9257-2c9ee7c9b3c2.png)
Mangalib
![Screenshot from 2021-07-23 11-34-45](https://user-images.githubusercontent.com/50526884/126757027-4952a7ac-1ce3-465b-9dc5-6d4de5c093bf.png)

### Описание

-------

closes #90

2021-07-23 09:38 UTC, dhvcc requested changes

2021-07-23 09:38 UTC, dhvcc commented on apps/parse/readmanga/list_parser/manga_spider.py
> -            try:
Рейтинг в лист вью нужен же

2021-07-23 09:42 UTC, NikDark commented on apps/parse/readmanga/list_parser/manga_spider.py
> -            try:
А его не всегда можно достать из list view. Например в мангалибе он в деталях только есть. Да и формат в ридманге на листвью не верный. 
Хотя поставь пока этот PR как WIP
Я попробую заинвестигейтить. Может можно получать на листвью везде и приводит к одному формату

2021-07-23 16:27 UTC, dhvcc commented on apps/parse/readmanga/list_parser/manga_spider.py
> -            try:
Ну пока changes requested висит

2021-07-26 08:36 UTC, NikDark commented
Так, еще наверное напишу migration чтобы перевела рейтинг который есть сейчас

2021-07-27 18:00 UTC, dhvcc approved these changes

2021-07-27 18:00 UTC, merged